### ISSUE TITLE
A few issues when running locally

### ISSUE THREAD

**Issue by umaar** [supabase-community/chatgpt-your-files#3] opened 2023-11-23 14:40 UTC
Seeing a few issues like:

```
[Info] Generated embedding {"table":"document_sections","id":71,"contentColumn":"content","embeddingColumn":"embedding"}

CPU time limit reached. isolate: 10342867669556939419
event loop error: Uncaught Error: execution terminated
failed to send request to user worker: connection closed before message completed
failed to send request to user worker: connection closed before message completed
InvalidWorkerResponse: user worker failed to respond
    at async Promise.all (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:64:19)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:128:12)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerResponse"
}
InvalidWorkerResponse: user worker failed to respond
    at async Promise.all (index 1)
    at async UserWorker.fetch (ext:sb_user_workers/user_workers.js:64:19)
    at async Server.<anonymous> (file:///home/deno/main/index.ts:128:12)
    at async Server.#respond (https://deno.land/std@0.182.0/http/server.ts:220:18) {
  name: "InvalidWorkerResponse"
}
serving the request with /home/deno/functions/chat
serving the request with /home/deno/functions/chat
```

And

```
[Info] Saved 25 sections for file 'roman-empire-3.md'

serving the request with /home/deno/functions/embed
serving the request with /home/deno/functions/embed
serving the request with /home/deno/functions/embed
client connection error (hyper::Error(IncompleteMessage))
client connection error (hyper::Error(IncompleteMessage))
client connection error (hyper::Error(IncompleteMessage))
[Info] Generated embedding {"table":"document_sections","id":66,"contentColumn":"content","embeddingColumn":"embedding"}
```

And:

```
 ⨯ node_modules/@xenova/transformers/src/env.js (60:0) @ eval
 ⨯ TypeError: Cannot read properties of undefined (reading 'wasm')
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at eval (./lib/hooks/use-pipeline.ts:5:78)
    at (ssr)/./lib/hooks/use-pipeline.ts (/code/chatgpt-your-files/.next/server/app/chat/page.js:423:1)
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at eval (./app/chat/page.tsx:10:81)
    at (ssr)/./app/chat/page.tsx (/code/chatgpt-your-files/.next/server/app/chat/page.js:357:1)
    at __webpack_require__ (/code/chatgpt-your-files/.next/server/webpack-runtime.js:33:43)
    at JSON.parse (<anonymous>)
null
```

- Running locally on macOS
- deno 1.38.2
- node v21.1.0
- supabase 1.102.0

Wondering what that could be about. Thanks for the great workshop!

**Comment by kleenkanteen** [comment] 2023-11-25 21:55
Try again te batch size got decreased: https://github.com/supabase-community/chatgpt-your-files/issues/2

**Comment by kleenkanteen** [comment] 2023-11-25 21:55
#3

**Comment by gregnr** [comment] 2023-11-28 19:53
Thank you for reporting @umaar. The CPU limit issues looks related to https://github.com/supabase-community/chatgpt-your-files/issues/2 - we'll open a PR shortly to get this into local dev. I'll look into the other issues!

**Comment by gregnr** [comment] 2023-11-29 17:40
Just an update - a pre-release version of the CLI is now available to test the new CPU limit logic. Feel free to try this by updating your `supabase` CLI dependency to v1.116.0 or above:

```shell
npm i -D supabase@1.116.0
```

**Comment by gregnr** [comment] 2024-01-05 21:46
An update - since my last comment this repo now uses the latest [Supabase CLI v1.127.4](https://github.com/supabase/cli/releases/tag/v1.127.4) which uses `edge-runtime` v1.29.1: https://github.com/supabase-community/chatgpt-your-files/pull/14

Of the errors above, I am still able to reproduce these errors:
```
client connection error (hyper::Error(IncompleteMessage))
```

and (intermittently): 

```
CPU time limit reached. isolate: ...
```

Will post updates as I learn more.

**Comment by gregnr** [comment] 2024-01-10 16:53
This error:
```
client connection error (hyper::Error(IncompleteMessage))
```

Has now been addressed in this PR: https://github.com/supabase-community/chatgpt-your-files/pull/15

The issue was due to `pg_net` closing the HTTP connection too early due to a timeout. Increasing the timeout removes this error.

**Closed** 2024-01-10 16:55 UTC
Labels: bug

**Comment by mlix8hoblc** [comment] 2024-01-24 17:58
@umaar what was the `TypeError: Cannot read properties of undefined (reading 'wasm')` about?
