### ISSUE TITLE
Cannot deploy SupabaseFunction anymore

### ISSUE THREAD

**Issue by enormousrodent** [supabase-community/chatgpt-your-files#12] opened 2023-12-27 15:48 UTC
# Bug report

## When deploying your function in repo i get an error

The error is the following:

error: Uncaught (in promise) Error: Relative import path "http" not prefixed with / or ./ or ../ and not in import map from "https://esm.sh/v135/@types/node@18.16.19/http.d.ts"
      const ret = new Error(getStringFromWasm0(arg0, arg1));

## To Reproduce

Try to deply the function in Supabase

## Expected behavior

Deploymen is successful

## Additional context

I have deployed this function last week and got it working no issues, but now it is failing.  It is like a sub module has changed / been updated

**Comment by gregnr** [comment] 2024-01-05 17:10
Hey @enormousrodent thanks for reporting. Can you please confirm:
- Which edge function is producing this error (`chat`, `embed`, `process`)?
- Do you receive this error during the upload process (`npx supabase functions deploy ...`), or at runtime after deploy?
- Any other errors to help us track down which dependency this could be related to (I agree - looks like a sub dependency of a module)

Thanks!

**Comment by gregnr** [comment] 2024-01-10 18:07
Hey, I just tried to reproduce this by deploying all three edge functions and testing them at runtime, but wasn't able to reproduce that error. Closing this issue for now, but feel free to comment if you still experience this.

**Closed by gregnr** 2024-01-10 18:07 UTC
Labels: bug
